// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

// CreateConfigurationResponseBody - App configuration created successfully
type CreateConfigurationResponseBody struct {
	AppID string `json:"app_id"`
}

func (o *CreateConfigurationResponseBody) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

type CreateConfigurationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// App configuration created successfully
	Object *CreateConfigurationResponseBody
}

func (o *CreateConfigurationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateConfigurationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateConfigurationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateConfigurationResponse) GetObject() *CreateConfigurationResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
