// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type CreateComponentRequest struct {
	BaseComponent shared.BaseComponentInput `request:"mediaType=application/json"`
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// Version to update
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (o *CreateComponentRequest) GetBaseComponent() shared.BaseComponentInput {
	if o == nil {
		return shared.BaseComponentInput{}
	}
	return o.BaseComponent
}

func (o *CreateComponentRequest) GetBaseComponentCustomFlowAction() *shared.CustomFlowActionComponentSchemas {
	return o.GetBaseComponent().CustomFlowActionComponentSchemas
}

func (o *CreateComponentRequest) GetBaseComponentCustomJourneyBlock() *shared.SchemasInput {
	return o.GetBaseComponent().SchemasInput
}

func (o *CreateComponentRequest) GetBaseComponentPortalExtension() *shared.PortalExtensionComponentSchemas {
	return o.GetBaseComponent().PortalExtensionComponentSchemas
}

func (o *CreateComponentRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *CreateComponentRequest) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

type CreateComponentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateComponentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateComponentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateComponentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
