// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
	"time"
)

type CreateBundleUploadURLRequest struct {
	CreateBundlePresignedRequest shared.CreateBundlePresignedRequest `request:"mediaType=application/json"`
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *CreateBundleUploadURLRequest) GetCreateBundlePresignedRequest() shared.CreateBundlePresignedRequest {
	if o == nil {
		return shared.CreateBundlePresignedRequest{}
	}
	return o.CreateBundlePresignedRequest
}

func (o *CreateBundleUploadURLRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

// CreateBundleUploadURLResponseBody - Upload URL generated successfully
type CreateBundleUploadURLResponseBody struct {
	// ID of the journye block component
	ComponentID *string `json:"component_id,omitempty"`
	// URL of the web component object
	ComponentURL *string `json:"component_url,omitempty"`
	// Timestamp when the upload URL expires
	ExpiresAt *time.Time          `json:"expires_at,omitempty"`
	S3ref     *shared.S3Reference `json:"s3ref,omitempty"`
	// Presigned S3 URL for uploading the bundle
	UploadURL string `json:"upload_url"`
}

func (c CreateBundleUploadURLResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateBundleUploadURLResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"upload_url"}); err != nil {
		return err
	}
	return nil
}

func (o *CreateBundleUploadURLResponseBody) GetComponentID() *string {
	if o == nil {
		return nil
	}
	return o.ComponentID
}

func (o *CreateBundleUploadURLResponseBody) GetComponentURL() *string {
	if o == nil {
		return nil
	}
	return o.ComponentURL
}

func (o *CreateBundleUploadURLResponseBody) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *CreateBundleUploadURLResponseBody) GetS3ref() *shared.S3Reference {
	if o == nil {
		return nil
	}
	return o.S3ref
}

func (o *CreateBundleUploadURLResponseBody) GetUploadURL() string {
	if o == nil {
		return ""
	}
	return o.UploadURL
}

type CreateBundleUploadURLResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Upload URL generated successfully
	Object *CreateBundleUploadURLResponseBody
}

func (o *CreateBundleUploadURLResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateBundleUploadURLResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateBundleUploadURLResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateBundleUploadURLResponse) GetObject() *CreateBundleUploadURLResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
