// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
	"time"
)

type CreateLogoUploadURLRequest struct {
	CreateLogoPresignedRequest shared.CreateLogoPresignedRequest `request:"mediaType=application/json"`
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
}

func (c *CreateLogoUploadURLRequest) GetCreateLogoPresignedRequest() shared.CreateLogoPresignedRequest {
	if c == nil {
		return shared.CreateLogoPresignedRequest{}
	}
	return c.CreateLogoPresignedRequest
}

func (c *CreateLogoUploadURLRequest) GetAppID() string {
	if c == nil {
		return ""
	}
	return c.AppID
}

// CreateLogoUploadURLResponseBody - Upload URL generated successfully
type CreateLogoUploadURLResponseBody struct {
	// Timestamp when the upload URL expires
	ExpiresAt *time.Time          `json:"expires_at,omitempty"`
	S3ref     *shared.S3Reference `json:"s3ref,omitempty"`
	// Presigned S3 URL for uploading the logo
	UploadURL string `json:"upload_url"`
}

func (c CreateLogoUploadURLResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateLogoUploadURLResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"upload_url"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateLogoUploadURLResponseBody) GetExpiresAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CreateLogoUploadURLResponseBody) GetS3ref() *shared.S3Reference {
	if c == nil {
		return nil
	}
	return c.S3ref
}

func (c *CreateLogoUploadURLResponseBody) GetUploadURL() string {
	if c == nil {
		return ""
	}
	return c.UploadURL
}

type CreateLogoUploadURLResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Upload URL generated successfully
	Object *CreateLogoUploadURLResponseBody
}

func (c *CreateLogoUploadURLResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateLogoUploadURLResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateLogoUploadURLResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateLogoUploadURLResponse) GetObject() *CreateLogoUploadURLResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
