// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteVersionRequest struct {
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// Version to delete
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (o *DeleteVersionRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *DeleteVersionRequest) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

type DeleteVersionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteVersionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteVersionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteVersionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
