// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteComponentRequest struct {
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// ID of the component to delete
	ComponentID string `pathParam:"style=simple,explode=false,name=componentId"`
	// Version to update
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (o *DeleteComponentRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *DeleteComponentRequest) GetComponentID() string {
	if o == nil {
		return ""
	}
	return o.ComponentID
}

func (o *DeleteComponentRequest) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

type DeleteComponentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteComponentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteComponentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteComponentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
