// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type GetAppConfigurationRequest struct {
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
}

func (o *GetAppConfigurationRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

type GetAppConfigurationResponse struct {
	// Successful response
	AppConfiguration *shared.AppConfiguration
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAppConfigurationResponse) GetAppConfiguration() *shared.AppConfiguration {
	if o == nil {
		return nil
	}
	return o.AppConfiguration
}

func (o *GetAppConfigurationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAppConfigurationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAppConfigurationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
