// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type GetConfigurationRequest struct {
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// Version of the app configuration to retrieve
	Version *string `queryParam:"style=form,explode=true,name=version"`
}

func (g *GetConfigurationRequest) GetAppID() string {
	if g == nil {
		return ""
	}
	return g.AppID
}

func (g *GetConfigurationRequest) GetVersion() *string {
	if g == nil {
		return nil
	}
	return g.Version
}

type GetConfigurationResponse struct {
	// Successful response
	Configuration *shared.Configuration
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetConfigurationResponse) GetConfiguration() *shared.Configuration {
	if g == nil {
		return nil
	}
	return g.Configuration
}

func (g *GetConfigurationResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetConfigurationResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetConfigurationResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
