// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type GetInstallationRequest struct {
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetInstallationRequest) GetAppID() string {
	if g == nil {
		return ""
	}
	return g.AppID
}

type GetInstallationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Details about an app installation.
	Installation *shared.Installation
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetInstallationResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetInstallationResponse) GetInstallation() *shared.Installation {
	if g == nil {
		return nil
	}
	return g.Installation
}

func (g *GetInstallationResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetInstallationResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
