// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type GetPublicConfigurationRequest struct {
	// ID of the app configuration to install
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// Version of the app configuration to retrieve
	Version *string `queryParam:"style=form,explode=true,name=version"`
}

func (o *GetPublicConfigurationRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *GetPublicConfigurationRequest) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

type GetPublicConfigurationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	PublicConfiguration *shared.PublicConfiguration
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetPublicConfigurationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPublicConfigurationResponse) GetPublicConfiguration() *shared.PublicConfiguration {
	if o == nil {
		return nil
	}
	return o.PublicConfiguration
}

func (o *GetPublicConfigurationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPublicConfigurationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
