// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type GetVersionRequest struct {
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// Version of the app configuration to retrieve
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (o *GetVersionRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *GetVersionRequest) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

type GetVersionResponse struct {
	// App configuration for specific version
	Configuration *shared.Configuration
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetVersionResponse) GetConfiguration() *shared.Configuration {
	if o == nil {
		return nil
	}
	return o.Configuration
}

func (o *GetVersionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetVersionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetVersionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
