// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type InstallRequest struct {
	InstallRequest *shared.InstallRequest `request:"mediaType=application/json"`
	AppID          string                 `pathParam:"style=simple,explode=false,name=appId"`
}

func (i *InstallRequest) GetInstallRequest() *shared.InstallRequest {
	if i == nil {
		return nil
	}
	return i.InstallRequest
}

func (i *InstallRequest) GetAppID() string {
	if i == nil {
		return ""
	}
	return i.AppID
}

type InstallResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// App successfully installed.
	Installation *shared.Installation
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (i *InstallResponse) GetContentType() string {
	if i == nil {
		return ""
	}
	return i.ContentType
}

func (i *InstallResponse) GetInstallation() *shared.Installation {
	if i == nil {
		return nil
	}
	return i.Installation
}

func (i *InstallResponse) GetStatusCode() int {
	if i == nil {
		return 0
	}
	return i.StatusCode
}

func (i *InstallResponse) GetRawResponse() *http.Response {
	if i == nil {
		return nil
	}
	return i.RawResponse
}
