// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type ListVersionsRequest struct {
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// Page number for pagination
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=pageSize"`
}

func (l ListVersionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListVersionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"appId"}); err != nil {
		return err
	}
	return nil
}

func (l *ListVersionsRequest) GetAppID() string {
	if l == nil {
		return ""
	}
	return l.AppID
}

func (l *ListVersionsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListVersionsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListVersionsPagination struct {
	Page     *int64 `json:"page,omitempty"`
	PageSize *int64 `json:"pageSize,omitempty"`
	Total    *int64 `json:"total,omitempty"`
}

func (l *ListVersionsPagination) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListVersionsPagination) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListVersionsPagination) GetTotal() *int64 {
	if l == nil {
		return nil
	}
	return l.Total
}

// ListVersionsResponseBody - List of app versions
type ListVersionsResponseBody struct {
	Pagination *ListVersionsPagination       `json:"pagination,omitempty"`
	Versions   []shared.ConfigurationVersion `json:"versions,omitempty"`
}

func (l *ListVersionsResponseBody) GetPagination() *ListVersionsPagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}

func (l *ListVersionsResponseBody) GetVersions() []shared.ConfigurationVersion {
	if l == nil {
		return nil
	}
	return l.Versions
}

type ListVersionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of app versions
	Object *ListVersionsResponseBody
}

func (l *ListVersionsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListVersionsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListVersionsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListVersionsResponse) GetObject() *ListVersionsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
