// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type ListConfigurationsRequest struct {
	// Page number for pagination
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=pageSize"`
}

func (l ListConfigurationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConfigurationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConfigurationsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListConfigurationsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type Pagination struct {
	Page     *int64 `json:"page,omitempty"`
	PageSize *int64 `json:"pageSize,omitempty"`
	Total    *int64 `json:"total,omitempty"`
}

func (p *Pagination) GetPage() *int64 {
	if p == nil {
		return nil
	}
	return p.Page
}

func (p *Pagination) GetPageSize() *int64 {
	if p == nil {
		return nil
	}
	return p.PageSize
}

func (p *Pagination) GetTotal() *int64 {
	if p == nil {
		return nil
	}
	return p.Total
}

// ListConfigurationsResponseBody - List of app configurations
type ListConfigurationsResponseBody struct {
	Configurations []shared.ConfigurationMetadata `json:"configurations,omitempty"`
	Pagination     *Pagination                    `json:"pagination,omitempty"`
}

func (l *ListConfigurationsResponseBody) GetConfigurations() []shared.ConfigurationMetadata {
	if l == nil {
		return nil
	}
	return l.Configurations
}

func (l *ListConfigurationsResponseBody) GetPagination() *Pagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}

type ListConfigurationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of app configurations
	Object *ListConfigurationsResponseBody
}

func (l *ListConfigurationsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListConfigurationsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListConfigurationsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListConfigurationsResponse) GetObject() *ListConfigurationsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
