// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type ListInstallationsRequest struct {
	// Filter apps by specific component type
	ComponentType *shared.ComponentType `queryParam:"style=form,explode=true,name=componentType"`
	// Filter apps by enabled status
	Enabled *bool `queryParam:"style=form,explode=true,name=enabled"`
	// Page number for pagination
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of items per page
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=pageSize"`
}

func (l ListInstallationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInstallationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInstallationsRequest) GetComponentType() *shared.ComponentType {
	if l == nil {
		return nil
	}
	return l.ComponentType
}

func (l *ListInstallationsRequest) GetEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.Enabled
}

func (l *ListInstallationsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListInstallationsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

type ListInstallationsPagination struct {
	Page     *int64 `json:"page,omitempty"`
	PageSize *int64 `json:"pageSize,omitempty"`
	Total    *int64 `json:"total,omitempty"`
}

func (l *ListInstallationsPagination) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListInstallationsPagination) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListInstallationsPagination) GetTotal() *int64 {
	if l == nil {
		return nil
	}
	return l.Total
}

// ListInstallationsResponseBody - Successful response
type ListInstallationsResponseBody struct {
	Apps       []shared.Installation        `json:"apps,omitempty"`
	Pagination *ListInstallationsPagination `json:"pagination,omitempty"`
}

func (l *ListInstallationsResponseBody) GetApps() []shared.Installation {
	if l == nil {
		return nil
	}
	return l.Apps
}

func (l *ListInstallationsResponseBody) GetPagination() *ListInstallationsPagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}

type ListInstallationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response
	Object *ListInstallationsResponseBody
}

func (l *ListInstallationsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListInstallationsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListInstallationsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListInstallationsResponse) GetObject() *ListInstallationsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
