// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type PatchVersionRequest struct {
	PatchVersionRequest shared.PatchVersionRequest `request:"mediaType=application/json"`
	// ID of the app configuration
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// Version to update
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (o *PatchVersionRequest) GetPatchVersionRequest() shared.PatchVersionRequest {
	if o == nil {
		return shared.PatchVersionRequest{}
	}
	return o.PatchVersionRequest
}

func (o *PatchVersionRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *PatchVersionRequest) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

type PatchVersionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PatchVersionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchVersionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchVersionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
