// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/shared"
	"net/http"
)

type PromoteVersionRequest struct {
	AppID   string `pathParam:"style=simple,explode=false,name=appId"`
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (o *PromoteVersionRequest) GetAppID() string {
	if o == nil {
		return ""
	}
	return o.AppID
}

func (o *PromoteVersionRequest) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

type PromoteVersionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// App successfully promoted to new version
	Installation *shared.Installation
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PromoteVersionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PromoteVersionResponse) GetInstallation() *shared.Installation {
	if o == nil {
		return nil
	}
	return o.Installation
}

func (o *PromoteVersionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PromoteVersionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
