// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/internal/utils"
)

type SchemasComponentType string

const (
	SchemasComponentTypeErpInformToolkit SchemasComponentType = "ERP_INFORM_TOOLKIT"
)

func (e SchemasComponentType) ToPointer() *SchemasComponentType {
	return &e
}
func (e *SchemasComponentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ERP_INFORM_TOOLKIT":
		*e = SchemasComponentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasComponentType: %v", v)
	}
}

type SchemasErpInformToolkitComponentType string

const (
	SchemasErpInformToolkitComponentTypeInbound  SchemasErpInformToolkitComponentType = "inbound"
	SchemasErpInformToolkitComponentTypeOutbound SchemasErpInformToolkitComponentType = "outbound"
)

func (e SchemasErpInformToolkitComponentType) ToPointer() *SchemasErpInformToolkitComponentType {
	return &e
}
func (e *SchemasErpInformToolkitComponentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "inbound":
		fallthrough
	case "outbound":
		*e = SchemasErpInformToolkitComponentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasErpInformToolkitComponentType: %v", v)
	}
}

type SchemasConfiguration struct {
	Type SchemasErpInformToolkitComponentType `json:"type"`
}

func (s SchemasConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasConfiguration) GetType() SchemasErpInformToolkitComponentType {
	if s == nil {
		return SchemasErpInformToolkitComponentType("")
	}
	return s.Type
}

// SchemasErpInformToolkitComponentDescription - Description of the component
type SchemasErpInformToolkitComponentDescription struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasErpInformToolkitComponentDescription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasErpInformToolkitComponentDescription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasErpInformToolkitComponentDescription) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasErpInformToolkitComponentDescription) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

// SchemasName - Name of the component
type SchemasName struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasName) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasName) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasName) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasName) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

type SchemasSurfaces struct {
}

func (s SchemasSurfaces) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasSurfaces) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

type ErpInformToolkitComponentSchemas struct {
	ComponentType SchemasComponentType                         `json:"component_type"`
	Configuration SchemasConfiguration                         `json:"configuration"`
	Description   *SchemasErpInformToolkitComponentDescription `json:"description,omitempty"`
	// Unique identifier for the component
	ID   string       `json:"id"`
	Name *SchemasName `json:"name,omitempty"`
	// List of options for the app component
	Options  []Options        `json:"options,omitempty"`
	Surfaces *SchemasSurfaces `json:"surfaces,omitempty"`
}

func (e ErpInformToolkitComponentSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ErpInformToolkitComponentSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"component_type", "configuration", "id"}); err != nil {
		return err
	}
	return nil
}

func (e *ErpInformToolkitComponentSchemas) GetComponentType() SchemasComponentType {
	if e == nil {
		return SchemasComponentType("")
	}
	return e.ComponentType
}

func (e *ErpInformToolkitComponentSchemas) GetConfiguration() SchemasConfiguration {
	if e == nil {
		return SchemasConfiguration{}
	}
	return e.Configuration
}

func (e *ErpInformToolkitComponentSchemas) GetDescription() *SchemasErpInformToolkitComponentDescription {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *ErpInformToolkitComponentSchemas) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *ErpInformToolkitComponentSchemas) GetName() *SchemasName {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *ErpInformToolkitComponentSchemas) GetOptions() []Options {
	if e == nil {
		return nil
	}
	return e.Options
}

func (e *ErpInformToolkitComponentSchemas) GetSurfaces() *SchemasSurfaces {
	if e == nil {
		return nil
	}
	return e.Surfaces
}

type SchemasCustomFlowActionComponentComponentType string

const (
	SchemasCustomFlowActionComponentComponentTypeCustomFlowAction SchemasCustomFlowActionComponentComponentType = "CUSTOM_FLOW_ACTION"
)

func (e SchemasCustomFlowActionComponentComponentType) ToPointer() *SchemasCustomFlowActionComponentComponentType {
	return &e
}
func (e *SchemasCustomFlowActionComponentComponentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CUSTOM_FLOW_ACTION":
		*e = SchemasCustomFlowActionComponentComponentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasCustomFlowActionComponentComponentType: %v", v)
	}
}

// SchemasDescription - Description of the component
type SchemasDescription struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasDescription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasDescription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasDescription) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasDescription) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

// Name of the component
type Name struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (n Name) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *Name) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (n *Name) GetDe() string {
	if n == nil {
		return ""
	}
	return n.De
}

func (n *Name) GetEn() *string {
	if n == nil {
		return nil
	}
	return n.En
}

type Surfaces struct {
}

func (s Surfaces) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Surfaces) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

type CustomFlowActionComponentSchemas struct {
	ComponentType SchemasCustomFlowActionComponentComponentType `json:"component_type"`
	Configuration CustomFlowConfig                              `json:"configuration"`
	Description   *SchemasDescription                           `json:"description,omitempty"`
	// Unique identifier for the component
	ID   string `json:"id"`
	Name *Name  `json:"name,omitempty"`
	// List of options for the app component
	Options  []Options `json:"options,omitempty"`
	Surfaces *Surfaces `json:"surfaces,omitempty"`
}

func (c CustomFlowActionComponentSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CustomFlowActionComponentSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"component_type", "configuration", "id"}); err != nil {
		return err
	}
	return nil
}

func (c *CustomFlowActionComponentSchemas) GetComponentType() SchemasCustomFlowActionComponentComponentType {
	if c == nil {
		return SchemasCustomFlowActionComponentComponentType("")
	}
	return c.ComponentType
}

func (c *CustomFlowActionComponentSchemas) GetConfiguration() CustomFlowConfig {
	if c == nil {
		return CustomFlowConfig{}
	}
	return c.Configuration
}

func (c *CustomFlowActionComponentSchemas) GetConfigurationExternalIntegration() *ExternalIntegrationCustomActionConfigSchemas {
	return c.GetConfiguration().ExternalIntegrationCustomActionConfigSchemas
}

func (c *CustomFlowActionComponentSchemas) GetDescription() *SchemasDescription {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomFlowActionComponentSchemas) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CustomFlowActionComponentSchemas) GetName() *Name {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomFlowActionComponentSchemas) GetOptions() []Options {
	if c == nil {
		return nil
	}
	return c.Options
}

func (c *CustomFlowActionComponentSchemas) GetSurfaces() *Surfaces {
	if c == nil {
		return nil
	}
	return c.Surfaces
}

type SchemasPortalExtensionComponentComponentType string

const (
	SchemasPortalExtensionComponentComponentTypePortalExtension SchemasPortalExtensionComponentComponentType = "PORTAL_EXTENSION"
)

func (e SchemasPortalExtensionComponentComponentType) ToPointer() *SchemasPortalExtensionComponentComponentType {
	return &e
}
func (e *SchemasPortalExtensionComponentComponentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PORTAL_EXTENSION":
		*e = SchemasPortalExtensionComponentComponentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasPortalExtensionComponentComponentType: %v", v)
	}
}

// SchemasPortalExtensionComponentDescription - Description of the component
type SchemasPortalExtensionComponentDescription struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasPortalExtensionComponentDescription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasPortalExtensionComponentDescription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasPortalExtensionComponentDescription) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasPortalExtensionComponentDescription) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

// SchemasPortalExtensionComponentName - Name of the component
type SchemasPortalExtensionComponentName struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasPortalExtensionComponentName) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasPortalExtensionComponentName) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasPortalExtensionComponentName) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasPortalExtensionComponentName) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

type Origin string

const (
	OriginEndCustomerPortal Origin = "END_CUSTOMER_PORTAL"
	OriginInstallerPortal   Origin = "INSTALLER_PORTAL"
)

func (e Origin) ToPointer() *Origin {
	return &e
}
func (e *Origin) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "END_CUSTOMER_PORTAL":
		fallthrough
	case "INSTALLER_PORTAL":
		*e = Origin(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Origin: %v", v)
	}
}

type SchemasPortalExtensionComponentSurfaces struct {
}

func (s SchemasPortalExtensionComponentSurfaces) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasPortalExtensionComponentSurfaces) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

type PortalExtensionComponentSchemas struct {
	ComponentType SchemasPortalExtensionComponentComponentType `json:"component_type"`
	Configuration PortalExtensionConfig                        `json:"configuration"`
	Description   *SchemasPortalExtensionComponentDescription  `json:"description,omitempty"`
	// Unique identifier for the component
	ID   string                               `json:"id"`
	Name *SchemasPortalExtensionComponentName `json:"name,omitempty"`
	// List of options for the app component
	Options  []Options                                `json:"options,omitempty"`
	Origin   *Origin                                  `json:"origin,omitempty"`
	Surfaces *SchemasPortalExtensionComponentSurfaces `json:"surfaces,omitempty"`
}

func (p PortalExtensionComponentSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PortalExtensionComponentSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"component_type", "configuration", "id"}); err != nil {
		return err
	}
	return nil
}

func (p *PortalExtensionComponentSchemas) GetComponentType() SchemasPortalExtensionComponentComponentType {
	if p == nil {
		return SchemasPortalExtensionComponentComponentType("")
	}
	return p.ComponentType
}

func (p *PortalExtensionComponentSchemas) GetConfiguration() PortalExtensionConfig {
	if p == nil {
		return PortalExtensionConfig{}
	}
	return p.Configuration
}

func (p *PortalExtensionComponentSchemas) GetDescription() *SchemasPortalExtensionComponentDescription {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PortalExtensionComponentSchemas) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PortalExtensionComponentSchemas) GetName() *SchemasPortalExtensionComponentName {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PortalExtensionComponentSchemas) GetOptions() []Options {
	if p == nil {
		return nil
	}
	return p.Options
}

func (p *PortalExtensionComponentSchemas) GetOrigin() *Origin {
	if p == nil {
		return nil
	}
	return p.Origin
}

func (p *PortalExtensionComponentSchemas) GetSurfaces() *SchemasPortalExtensionComponentSurfaces {
	if p == nil {
		return nil
	}
	return p.Surfaces
}

type SchemasJourneyBlockComponentComponentType string

const (
	SchemasJourneyBlockComponentComponentTypeCustomJourneyBlock SchemasJourneyBlockComponentComponentType = "CUSTOM_JOURNEY_BLOCK"
)

func (e SchemasJourneyBlockComponentComponentType) ToPointer() *SchemasJourneyBlockComponentComponentType {
	return &e
}
func (e *SchemasJourneyBlockComponentComponentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CUSTOM_JOURNEY_BLOCK":
		*e = SchemasJourneyBlockComponentComponentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasJourneyBlockComponentComponentType: %v", v)
	}
}

// SchemasJourneyBlockComponentDescription - Description of the component
type SchemasJourneyBlockComponentDescription struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasJourneyBlockComponentDescription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasJourneyBlockComponentDescription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasJourneyBlockComponentDescription) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasJourneyBlockComponentDescription) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

// SchemasJourneyBlockComponentName - Name of the component
type SchemasJourneyBlockComponentName struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasJourneyBlockComponentName) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasJourneyBlockComponentName) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasJourneyBlockComponentName) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasJourneyBlockComponentName) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

type SchemasJourneyBlockComponentSurfaces struct {
}

func (s SchemasJourneyBlockComponentSurfaces) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasJourneyBlockComponentSurfaces) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

type JourneyBlockComponentSchemas struct {
	ComponentType SchemasJourneyBlockComponentComponentType `json:"component_type"`
	Configuration JourneyBlockConfig                        `json:"configuration"`
	Description   *SchemasJourneyBlockComponentDescription  `json:"description,omitempty"`
	// Unique identifier for the component
	ID   string                            `json:"id"`
	Name *SchemasJourneyBlockComponentName `json:"name,omitempty"`
	// List of options for the app component
	Options  []Options                             `json:"options,omitempty"`
	Surfaces *SchemasJourneyBlockComponentSurfaces `json:"surfaces,omitempty"`
}

func (j JourneyBlockComponentSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JourneyBlockComponentSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, []string{"component_type", "configuration", "id"}); err != nil {
		return err
	}
	return nil
}

func (j *JourneyBlockComponentSchemas) GetComponentType() SchemasJourneyBlockComponentComponentType {
	if j == nil {
		return SchemasJourneyBlockComponentComponentType("")
	}
	return j.ComponentType
}

func (j *JourneyBlockComponentSchemas) GetConfiguration() JourneyBlockConfig {
	if j == nil {
		return JourneyBlockConfig{}
	}
	return j.Configuration
}

func (j *JourneyBlockComponentSchemas) GetDescription() *SchemasJourneyBlockComponentDescription {
	if j == nil {
		return nil
	}
	return j.Description
}

func (j *JourneyBlockComponentSchemas) GetID() string {
	if j == nil {
		return ""
	}
	return j.ID
}

func (j *JourneyBlockComponentSchemas) GetName() *SchemasJourneyBlockComponentName {
	if j == nil {
		return nil
	}
	return j.Name
}

func (j *JourneyBlockComponentSchemas) GetOptions() []Options {
	if j == nil {
		return nil
	}
	return j.Options
}

func (j *JourneyBlockComponentSchemas) GetSurfaces() *SchemasJourneyBlockComponentSurfaces {
	if j == nil {
		return nil
	}
	return j.Surfaces
}

type BaseComponentType string

const (
	BaseComponentTypeCustomFlowAction   BaseComponentType = "CUSTOM_FLOW_ACTION"
	BaseComponentTypeCustomJourneyBlock BaseComponentType = "CUSTOM_JOURNEY_BLOCK"
	BaseComponentTypeErpInformToolkit   BaseComponentType = "ERP_INFORM_TOOLKIT"
	BaseComponentTypePortalExtension    BaseComponentType = "PORTAL_EXTENSION"
)

type BaseComponent struct {
	JourneyBlockComponentSchemas     *JourneyBlockComponentSchemas     `queryParam:"inline" name:"BaseComponent"`
	PortalExtensionComponentSchemas  *PortalExtensionComponentSchemas  `queryParam:"inline" name:"BaseComponent"`
	CustomFlowActionComponentSchemas *CustomFlowActionComponentSchemas `queryParam:"inline" name:"BaseComponent"`
	ErpInformToolkitComponentSchemas *ErpInformToolkitComponentSchemas `queryParam:"inline" name:"BaseComponent"`

	Type BaseComponentType
}

func CreateBaseComponentCustomFlowAction(customFlowAction CustomFlowActionComponentSchemas) BaseComponent {
	typ := BaseComponentTypeCustomFlowAction

	typStr := SchemasCustomFlowActionComponentComponentType(typ)
	customFlowAction.ComponentType = typStr

	return BaseComponent{
		CustomFlowActionComponentSchemas: &customFlowAction,
		Type:                             typ,
	}
}

func CreateBaseComponentCustomJourneyBlock(customJourneyBlock JourneyBlockComponentSchemas) BaseComponent {
	typ := BaseComponentTypeCustomJourneyBlock

	typStr := SchemasJourneyBlockComponentComponentType(typ)
	customJourneyBlock.ComponentType = typStr

	return BaseComponent{
		JourneyBlockComponentSchemas: &customJourneyBlock,
		Type:                         typ,
	}
}

func CreateBaseComponentErpInformToolkit(erpInformToolkit ErpInformToolkitComponentSchemas) BaseComponent {
	typ := BaseComponentTypeErpInformToolkit

	typStr := SchemasComponentType(typ)
	erpInformToolkit.ComponentType = typStr

	return BaseComponent{
		ErpInformToolkitComponentSchemas: &erpInformToolkit,
		Type:                             typ,
	}
}

func CreateBaseComponentPortalExtension(portalExtension PortalExtensionComponentSchemas) BaseComponent {
	typ := BaseComponentTypePortalExtension

	typStr := SchemasPortalExtensionComponentComponentType(typ)
	portalExtension.ComponentType = typStr

	return BaseComponent{
		PortalExtensionComponentSchemas: &portalExtension,
		Type:                            typ,
	}
}

func (u *BaseComponent) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		ComponentType string `json:"component_type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.ComponentType {
	case "CUSTOM_FLOW_ACTION":
		customFlowActionComponentSchemas := new(CustomFlowActionComponentSchemas)
		if err := utils.UnmarshalJSON(data, &customFlowActionComponentSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ComponentType == CUSTOM_FLOW_ACTION) type CustomFlowActionComponentSchemas within BaseComponent: %w", string(data), err)
		}

		u.CustomFlowActionComponentSchemas = customFlowActionComponentSchemas
		u.Type = BaseComponentTypeCustomFlowAction
		return nil
	case "CUSTOM_JOURNEY_BLOCK":
		journeyBlockComponentSchemas := new(JourneyBlockComponentSchemas)
		if err := utils.UnmarshalJSON(data, &journeyBlockComponentSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ComponentType == CUSTOM_JOURNEY_BLOCK) type JourneyBlockComponentSchemas within BaseComponent: %w", string(data), err)
		}

		u.JourneyBlockComponentSchemas = journeyBlockComponentSchemas
		u.Type = BaseComponentTypeCustomJourneyBlock
		return nil
	case "ERP_INFORM_TOOLKIT":
		erpInformToolkitComponentSchemas := new(ErpInformToolkitComponentSchemas)
		if err := utils.UnmarshalJSON(data, &erpInformToolkitComponentSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ComponentType == ERP_INFORM_TOOLKIT) type ErpInformToolkitComponentSchemas within BaseComponent: %w", string(data), err)
		}

		u.ErpInformToolkitComponentSchemas = erpInformToolkitComponentSchemas
		u.Type = BaseComponentTypeErpInformToolkit
		return nil
	case "PORTAL_EXTENSION":
		portalExtensionComponentSchemas := new(PortalExtensionComponentSchemas)
		if err := utils.UnmarshalJSON(data, &portalExtensionComponentSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ComponentType == PORTAL_EXTENSION) type PortalExtensionComponentSchemas within BaseComponent: %w", string(data), err)
		}

		u.PortalExtensionComponentSchemas = portalExtensionComponentSchemas
		u.Type = BaseComponentTypePortalExtension
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BaseComponent", string(data))
}

func (u BaseComponent) MarshalJSON() ([]byte, error) {
	if u.JourneyBlockComponentSchemas != nil {
		return utils.MarshalJSON(u.JourneyBlockComponentSchemas, "", true)
	}

	if u.PortalExtensionComponentSchemas != nil {
		return utils.MarshalJSON(u.PortalExtensionComponentSchemas, "", true)
	}

	if u.CustomFlowActionComponentSchemas != nil {
		return utils.MarshalJSON(u.CustomFlowActionComponentSchemas, "", true)
	}

	if u.ErpInformToolkitComponentSchemas != nil {
		return utils.MarshalJSON(u.ErpInformToolkitComponentSchemas, "", true)
	}

	return nil, errors.New("could not marshal union type BaseComponent: all fields are null")
}

type SchemasInput struct {
	ComponentType SchemasJourneyBlockComponentComponentType `json:"component_type"`
	Configuration JourneyBlockConfigInput                   `json:"configuration"`
	Description   *SchemasJourneyBlockComponentDescription  `json:"description,omitempty"`
	// Unique identifier for the component
	ID   string                            `json:"id"`
	Name *SchemasJourneyBlockComponentName `json:"name,omitempty"`
	// List of options for the app component
	Options  []Options                             `json:"options,omitempty"`
	Surfaces *SchemasJourneyBlockComponentSurfaces `json:"surfaces,omitempty"`
}

func (s SchemasInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"component_type", "configuration", "id"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasInput) GetComponentType() SchemasJourneyBlockComponentComponentType {
	if s == nil {
		return SchemasJourneyBlockComponentComponentType("")
	}
	return s.ComponentType
}

func (s *SchemasInput) GetConfiguration() JourneyBlockConfigInput {
	if s == nil {
		return JourneyBlockConfigInput{}
	}
	return s.Configuration
}

func (s *SchemasInput) GetDescription() *SchemasJourneyBlockComponentDescription {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SchemasInput) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SchemasInput) GetName() *SchemasJourneyBlockComponentName {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SchemasInput) GetOptions() []Options {
	if s == nil {
		return nil
	}
	return s.Options
}

func (s *SchemasInput) GetSurfaces() *SchemasJourneyBlockComponentSurfaces {
	if s == nil {
		return nil
	}
	return s.Surfaces
}

type BaseComponentInputType string

const (
	BaseComponentInputTypeCustomFlowAction   BaseComponentInputType = "CUSTOM_FLOW_ACTION"
	BaseComponentInputTypeCustomJourneyBlock BaseComponentInputType = "CUSTOM_JOURNEY_BLOCK"
	BaseComponentInputTypeErpInformToolkit   BaseComponentInputType = "ERP_INFORM_TOOLKIT"
	BaseComponentInputTypePortalExtension    BaseComponentInputType = "PORTAL_EXTENSION"
)

type BaseComponentInput struct {
	SchemasInput                     *SchemasInput                     `queryParam:"inline" name:"BaseComponent"`
	PortalExtensionComponentSchemas  *PortalExtensionComponentSchemas  `queryParam:"inline" name:"BaseComponent"`
	CustomFlowActionComponentSchemas *CustomFlowActionComponentSchemas `queryParam:"inline" name:"BaseComponent"`
	ErpInformToolkitComponentSchemas *ErpInformToolkitComponentSchemas `queryParam:"inline" name:"BaseComponent"`

	Type BaseComponentInputType
}

func CreateBaseComponentInputCustomFlowAction(customFlowAction CustomFlowActionComponentSchemas) BaseComponentInput {
	typ := BaseComponentInputTypeCustomFlowAction

	typStr := SchemasCustomFlowActionComponentComponentType(typ)
	customFlowAction.ComponentType = typStr

	return BaseComponentInput{
		CustomFlowActionComponentSchemas: &customFlowAction,
		Type:                             typ,
	}
}

func CreateBaseComponentInputCustomJourneyBlock(customJourneyBlock SchemasInput) BaseComponentInput {
	typ := BaseComponentInputTypeCustomJourneyBlock

	typStr := SchemasJourneyBlockComponentComponentType(typ)
	customJourneyBlock.ComponentType = typStr

	return BaseComponentInput{
		SchemasInput: &customJourneyBlock,
		Type:         typ,
	}
}

func CreateBaseComponentInputErpInformToolkit(erpInformToolkit ErpInformToolkitComponentSchemas) BaseComponentInput {
	typ := BaseComponentInputTypeErpInformToolkit

	typStr := SchemasComponentType(typ)
	erpInformToolkit.ComponentType = typStr

	return BaseComponentInput{
		ErpInformToolkitComponentSchemas: &erpInformToolkit,
		Type:                             typ,
	}
}

func CreateBaseComponentInputPortalExtension(portalExtension PortalExtensionComponentSchemas) BaseComponentInput {
	typ := BaseComponentInputTypePortalExtension

	typStr := SchemasPortalExtensionComponentComponentType(typ)
	portalExtension.ComponentType = typStr

	return BaseComponentInput{
		PortalExtensionComponentSchemas: &portalExtension,
		Type:                            typ,
	}
}

func (u *BaseComponentInput) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		ComponentType string `json:"component_type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.ComponentType {
	case "CUSTOM_FLOW_ACTION":
		customFlowActionComponentSchemas := new(CustomFlowActionComponentSchemas)
		if err := utils.UnmarshalJSON(data, &customFlowActionComponentSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ComponentType == CUSTOM_FLOW_ACTION) type CustomFlowActionComponentSchemas within BaseComponentInput: %w", string(data), err)
		}

		u.CustomFlowActionComponentSchemas = customFlowActionComponentSchemas
		u.Type = BaseComponentInputTypeCustomFlowAction
		return nil
	case "CUSTOM_JOURNEY_BLOCK":
		schemasInput := new(SchemasInput)
		if err := utils.UnmarshalJSON(data, &schemasInput, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ComponentType == CUSTOM_JOURNEY_BLOCK) type SchemasInput within BaseComponentInput: %w", string(data), err)
		}

		u.SchemasInput = schemasInput
		u.Type = BaseComponentInputTypeCustomJourneyBlock
		return nil
	case "ERP_INFORM_TOOLKIT":
		erpInformToolkitComponentSchemas := new(ErpInformToolkitComponentSchemas)
		if err := utils.UnmarshalJSON(data, &erpInformToolkitComponentSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ComponentType == ERP_INFORM_TOOLKIT) type ErpInformToolkitComponentSchemas within BaseComponentInput: %w", string(data), err)
		}

		u.ErpInformToolkitComponentSchemas = erpInformToolkitComponentSchemas
		u.Type = BaseComponentInputTypeErpInformToolkit
		return nil
	case "PORTAL_EXTENSION":
		portalExtensionComponentSchemas := new(PortalExtensionComponentSchemas)
		if err := utils.UnmarshalJSON(data, &portalExtensionComponentSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ComponentType == PORTAL_EXTENSION) type PortalExtensionComponentSchemas within BaseComponentInput: %w", string(data), err)
		}

		u.PortalExtensionComponentSchemas = portalExtensionComponentSchemas
		u.Type = BaseComponentInputTypePortalExtension
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BaseComponentInput", string(data))
}

func (u BaseComponentInput) MarshalJSON() ([]byte, error) {
	if u.SchemasInput != nil {
		return utils.MarshalJSON(u.SchemasInput, "", true)
	}

	if u.PortalExtensionComponentSchemas != nil {
		return utils.MarshalJSON(u.PortalExtensionComponentSchemas, "", true)
	}

	if u.CustomFlowActionComponentSchemas != nil {
		return utils.MarshalJSON(u.CustomFlowActionComponentSchemas, "", true)
	}

	if u.ErpInformToolkitComponentSchemas != nil {
		return utils.MarshalJSON(u.ErpInformToolkitComponentSchemas, "", true)
	}

	return nil, errors.New("could not marshal union type BaseComponentInput: all fields are null")
}
