// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BatchEventRequest struct {
	Events []AppEventDataInput `json:"events"`
}

func (o *BatchEventRequest) GetEvents() []AppEventDataInput {
	if o == nil {
		return []AppEventDataInput{}
	}
	return o.Events
}
