// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// BillingFrequency - How often the subscription is billed
type BillingFrequency string

const (
	BillingFrequencyMonthly   BillingFrequency = "MONTHLY"
	BillingFrequencyQuarterly BillingFrequency = "QUARTERLY"
	BillingFrequencyYearly    BillingFrequency = "YEARLY"
	BillingFrequencyCustom    BillingFrequency = "CUSTOM"
)

func (e BillingFrequency) ToPointer() *BillingFrequency {
	return &e
}
func (e *BillingFrequency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MONTHLY":
		fallthrough
	case "QUARTERLY":
		fallthrough
	case "YEARLY":
		fallthrough
	case "CUSTOM":
		*e = BillingFrequency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingFrequency: %v", v)
	}
}
