// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BlueprintRef struct {
	// ID of the job that created the blueprint
	JobID *string `json:"job_id,omitempty"`
	// ID of the blueprint
	ManifestID *string `json:"manifest_id,omitempty"`
}

func (b *BlueprintRef) GetJobID() *string {
	if b == nil {
		return nil
	}
	return b.JobID
}

func (b *BlueprintRef) GetManifestID() *string {
	if b == nil {
		return nil
	}
	return b.ManifestID
}
