// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateConfigRequest struct {
	Category    *string          `json:"category,omitempty"`
	Description TranslatedString `json:"description"`
	// S3 key of the logo file
	LogoURLKey *string `json:"logo_url_key,omitempty"`
	// Name of the app
	Name string `json:"name"`
}

func (o *CreateConfigRequest) GetCategory() *string {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *CreateConfigRequest) GetDescription() TranslatedString {
	if o == nil {
		return TranslatedString{}
	}
	return o.Description
}

func (o *CreateConfigRequest) GetLogoURLKey() *string {
	if o == nil {
		return nil
	}
	return o.LogoURLKey
}

func (o *CreateConfigRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
