// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Grants struct {
	// The action the app can perform
	Action string `json:"action"`
	// The resource the app can access
	Resource *string `json:"resource,omitempty"`
}

func (g *Grants) GetAction() string {
	if g == nil {
		return ""
	}
	return g.Action
}

func (g *Grants) GetResource() *string {
	if g == nil {
		return nil
	}
	return g.Resource
}
