// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type InstallRequest struct {
	// Configuration values for the app components
	OptionValues []OptionsRef `json:"option_values,omitempty"`
}

func (o *InstallRequest) GetOptionValues() []OptionsRef {
	if o == nil {
		return nil
	}
	return o.OptionValues
}
