// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/internal/utils"
)

// InstallationAudit - Audit information for the app
type InstallationAudit struct {
	// Timestamp of the creation
	CreatedAt *string `json:"created_at,omitempty"`
	// User ID of the creator
	CreatedBy *string `json:"created_by,omitempty"`
	// Timestamp of the last update
	UpdatedAt *string `json:"updated_at,omitempty"`
	// User ID of the last updater
	UpdatedBy *string `json:"updated_by,omitempty"`
}

func (i *InstallationAudit) GetCreatedAt() *string {
	if i == nil {
		return nil
	}
	return i.CreatedAt
}

func (i *InstallationAudit) GetCreatedBy() *string {
	if i == nil {
		return nil
	}
	return i.CreatedBy
}

func (i *InstallationAudit) GetUpdatedAt() *string {
	if i == nil {
		return nil
	}
	return i.UpdatedAt
}

func (i *InstallationAudit) GetUpdatedBy() *string {
	if i == nil {
		return nil
	}
	return i.UpdatedBy
}

// Installation - Information about the installed app. Has configuration data of the installed version
type Installation struct {
	// Manifest ID used to create/update the entity
	Manifest []string `json:"_manifest,omitempty"`
	// ID of the app configuration
	AppID        string        `json:"app_id"`
	BlueprintRef *BlueprintRef `json:"blueprint_ref,omitempty"`
	// List of component configurations for the installed version
	Components any `json:"components"`
	// Flag to indicate if the app is enabled. Enabled is set to true when required option values are set.
	Enabled           *bool              `default:"true" json:"enabled"`
	InstallationAudit *InstallationAudit `json:"installation_audit,omitempty"`
	// Version of the app that is installed
	InstalledVersion string `json:"installed_version"`
	// Unique identifier for the organization the app is installed in
	InstallerOrgID string `json:"installer_org_id"`
	// Name of the app
	Name string `json:"name"`
	// Configuration values for the app components
	OptionValues []OptionsRef `json:"option_values,omitempty"`
	// Organization ID of the app creator
	OwnerOrgID *string `json:"owner_org_id,omitempty"`
	// The name of the role the app can use to access APIs
	Role *string `json:"role,omitempty"`
}

func (i Installation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Installation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"app_id", "components", "installed_version", "installer_org_id", "name"}); err != nil {
		return err
	}
	return nil
}

func (i *Installation) GetManifest() []string {
	if i == nil {
		return nil
	}
	return i.Manifest
}

func (i *Installation) GetAppID() string {
	if i == nil {
		return ""
	}
	return i.AppID
}

func (i *Installation) GetBlueprintRef() *BlueprintRef {
	if i == nil {
		return nil
	}
	return i.BlueprintRef
}

func (i *Installation) GetComponents() any {
	if i == nil {
		return nil
	}
	return i.Components
}

func (i *Installation) GetEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.Enabled
}

func (i *Installation) GetInstallationAudit() *InstallationAudit {
	if i == nil {
		return nil
	}
	return i.InstallationAudit
}

func (i *Installation) GetInstalledVersion() string {
	if i == nil {
		return ""
	}
	return i.InstalledVersion
}

func (i *Installation) GetInstallerOrgID() string {
	if i == nil {
		return ""
	}
	return i.InstallerOrgID
}

func (i *Installation) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

func (i *Installation) GetOptionValues() []OptionsRef {
	if i == nil {
		return nil
	}
	return i.OptionValues
}

func (i *Installation) GetOwnerOrgID() *string {
	if i == nil {
		return nil
	}
	return i.OwnerOrgID
}

func (i *Installation) GetRole() *string {
	if i == nil {
		return nil
	}
	return i.Role
}
