// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/internal/utils"
)

// SchemasEnumArgDescription - Description of what this component arg does
type SchemasEnumArgDescription struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasEnumArgDescription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasEnumArgDescription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasEnumArgDescription) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasEnumArgDescription) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

// SchemasLabel - Human-readable label for the component arg
type SchemasLabel struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasLabel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasLabel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasLabel) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasLabel) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

// SchemasEnumArgLabel - Display label for the option
type SchemasEnumArgLabel struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasEnumArgLabel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasEnumArgLabel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasEnumArgLabel) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasEnumArgLabel) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

type SchemasOptions struct {
	// Unique identifier for the option
	ID    string              `json:"id"`
	Label SchemasEnumArgLabel `json:"label"`
}

func (s SchemasOptions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasOptions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"id", "label"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasOptions) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SchemasOptions) GetLabel() SchemasEnumArgLabel {
	if s == nil {
		return SchemasEnumArgLabel{}
	}
	return s.Label
}

type SchemasType string

const (
	SchemasTypeText    SchemasType = "text"
	SchemasTypeBoolean SchemasType = "boolean"
	SchemasTypeEnum    SchemasType = "enum"
)

func (e SchemasType) ToPointer() *SchemasType {
	return &e
}
func (e *SchemasType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "boolean":
		fallthrough
	case "enum":
		*e = SchemasType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasType: %v", v)
	}
}

type EnumArgSchemas struct {
	Description *SchemasEnumArgDescription `json:"description,omitempty"`
	// If true, allows selection of multiple values
	IsMulti *bool `default:"false" json:"isMulti"`
	// Unique identifier for this component arg
	Key   string       `json:"key"`
	Label SchemasLabel `json:"label"`
	// List of options for enum type
	Options []SchemasOptions `json:"options"`
	// Flag to indicate if this option is required
	Required *bool       `default:"false" json:"required"`
	Type     SchemasType `json:"type"`
}

func (e EnumArgSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnumArgSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"key", "label", "options", "type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnumArgSchemas) GetDescription() *SchemasEnumArgDescription {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *EnumArgSchemas) GetIsMulti() *bool {
	if e == nil {
		return nil
	}
	return e.IsMulti
}

func (e *EnumArgSchemas) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *EnumArgSchemas) GetLabel() SchemasLabel {
	if e == nil {
		return SchemasLabel{}
	}
	return e.Label
}

func (e *EnumArgSchemas) GetOptions() []SchemasOptions {
	if e == nil {
		return []SchemasOptions{}
	}
	return e.Options
}

func (e *EnumArgSchemas) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnumArgSchemas) GetType() SchemasType {
	if e == nil {
		return SchemasType("")
	}
	return e.Type
}

// Description of what this component arg does
type Description struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (d Description) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Description) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (d *Description) GetDe() string {
	if d == nil {
		return ""
	}
	return d.De
}

func (d *Description) GetEn() *string {
	if d == nil {
		return nil
	}
	return d.En
}

// Label - Human-readable label for the component arg
type Label struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (l Label) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *Label) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (l *Label) GetDe() string {
	if l == nil {
		return ""
	}
	return l.De
}

func (l *Label) GetEn() *string {
	if l == nil {
		return nil
	}
	return l.En
}

type Type string

const (
	TypeText    Type = "text"
	TypeBoolean Type = "boolean"
	TypeEnum    Type = "enum"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "boolean":
		fallthrough
	case "enum":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type Schemas struct {
	Description *Description `json:"description,omitempty"`
	// Unique identifier for this component arg
	Key   string `json:"key"`
	Label Label  `json:"label"`
	// Flag to indicate if this option is required
	Required *bool `default:"false" json:"required"`
	Type     Type  `json:"type"`
}

func (s Schemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Schemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"key", "label", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *Schemas) GetDescription() *Description {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *Schemas) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *Schemas) GetLabel() Label {
	if s == nil {
		return Label{}
	}
	return s.Label
}

func (s *Schemas) GetRequired() *bool {
	if s == nil {
		return nil
	}
	return s.Required
}

func (s *Schemas) GetType() Type {
	if s == nil {
		return Type("")
	}
	return s.Type
}

// SchemasTextArgDescription - Description of what this component arg does
type SchemasTextArgDescription struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasTextArgDescription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasTextArgDescription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasTextArgDescription) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasTextArgDescription) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

// SchemasTextArgLabel - Human-readable label for the component arg
type SchemasTextArgLabel struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (s SchemasTextArgLabel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasTextArgLabel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"de"}); err != nil {
		return err
	}
	return nil
}

func (s *SchemasTextArgLabel) GetDe() string {
	if s == nil {
		return ""
	}
	return s.De
}

func (s *SchemasTextArgLabel) GetEn() *string {
	if s == nil {
		return nil
	}
	return s.En
}

type SchemasTextArgType string

const (
	SchemasTextArgTypeText    SchemasTextArgType = "text"
	SchemasTextArgTypeBoolean SchemasTextArgType = "boolean"
	SchemasTextArgTypeEnum    SchemasTextArgType = "enum"
)

func (e SchemasTextArgType) ToPointer() *SchemasTextArgType {
	return &e
}
func (e *SchemasTextArgType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "boolean":
		fallthrough
	case "enum":
		*e = SchemasTextArgType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasTextArgType: %v", v)
	}
}

type TextArgSchemas struct {
	Description *SchemasTextArgDescription `json:"description,omitempty"`
	// Unique identifier for this component arg
	Key   string              `json:"key"`
	Label SchemasTextArgLabel `json:"label"`
	// Flag to indicate if this option is required
	Required *bool              `default:"false" json:"required"`
	Type     SchemasTextArgType `json:"type"`
}

func (t TextArgSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TextArgSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"key", "label", "type"}); err != nil {
		return err
	}
	return nil
}

func (t *TextArgSchemas) GetDescription() *SchemasTextArgDescription {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *TextArgSchemas) GetKey() string {
	if t == nil {
		return ""
	}
	return t.Key
}

func (t *TextArgSchemas) GetLabel() SchemasTextArgLabel {
	if t == nil {
		return SchemasTextArgLabel{}
	}
	return t.Label
}

func (t *TextArgSchemas) GetRequired() *bool {
	if t == nil {
		return nil
	}
	return t.Required
}

func (t *TextArgSchemas) GetType() SchemasTextArgType {
	if t == nil {
		return SchemasTextArgType("")
	}
	return t.Type
}

type JourneyBlockComponentArgsType string

const (
	JourneyBlockComponentArgsTypeBoolean JourneyBlockComponentArgsType = "boolean"
	JourneyBlockComponentArgsTypeEnum    JourneyBlockComponentArgsType = "enum"
	JourneyBlockComponentArgsTypeText    JourneyBlockComponentArgsType = "text"
)

type JourneyBlockComponentArgs struct {
	TextArgSchemas *TextArgSchemas `queryParam:"inline" name:"JourneyBlockComponentArgs"`
	Schemas        *Schemas        `queryParam:"inline" name:"JourneyBlockComponentArgs"`
	EnumArgSchemas *EnumArgSchemas `queryParam:"inline" name:"JourneyBlockComponentArgs"`

	Type JourneyBlockComponentArgsType
}

func CreateJourneyBlockComponentArgsBoolean(boolean Schemas) JourneyBlockComponentArgs {
	typ := JourneyBlockComponentArgsTypeBoolean

	typStr := Type(typ)
	boolean.Type = typStr

	return JourneyBlockComponentArgs{
		Schemas: &boolean,
		Type:    typ,
	}
}

func CreateJourneyBlockComponentArgsEnum(enum EnumArgSchemas) JourneyBlockComponentArgs {
	typ := JourneyBlockComponentArgsTypeEnum

	typStr := SchemasType(typ)
	enum.Type = typStr

	return JourneyBlockComponentArgs{
		EnumArgSchemas: &enum,
		Type:           typ,
	}
}

func CreateJourneyBlockComponentArgsText(text TextArgSchemas) JourneyBlockComponentArgs {
	typ := JourneyBlockComponentArgsTypeText

	typStr := SchemasTextArgType(typ)
	text.Type = typStr

	return JourneyBlockComponentArgs{
		TextArgSchemas: &text,
		Type:           typ,
	}
}

func (u *JourneyBlockComponentArgs) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "boolean":
		schemas := new(Schemas)
		if err := utils.UnmarshalJSON(data, &schemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == boolean) type Schemas within JourneyBlockComponentArgs: %w", string(data), err)
		}

		u.Schemas = schemas
		u.Type = JourneyBlockComponentArgsTypeBoolean
		return nil
	case "enum":
		enumArgSchemas := new(EnumArgSchemas)
		if err := utils.UnmarshalJSON(data, &enumArgSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == enum) type EnumArgSchemas within JourneyBlockComponentArgs: %w", string(data), err)
		}

		u.EnumArgSchemas = enumArgSchemas
		u.Type = JourneyBlockComponentArgsTypeEnum
		return nil
	case "text":
		textArgSchemas := new(TextArgSchemas)
		if err := utils.UnmarshalJSON(data, &textArgSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == text) type TextArgSchemas within JourneyBlockComponentArgs: %w", string(data), err)
		}

		u.TextArgSchemas = textArgSchemas
		u.Type = JourneyBlockComponentArgsTypeText
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for JourneyBlockComponentArgs", string(data))
}

func (u JourneyBlockComponentArgs) MarshalJSON() ([]byte, error) {
	if u.TextArgSchemas != nil {
		return utils.MarshalJSON(u.TextArgSchemas, "", true)
	}

	if u.Schemas != nil {
		return utils.MarshalJSON(u.Schemas, "", true)
	}

	if u.EnumArgSchemas != nil {
		return utils.MarshalJSON(u.EnumArgSchemas, "", true)
	}

	return nil, errors.New("could not marshal union type JourneyBlockComponentArgs: all fields are null")
}
