// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type JourneyBlockConfig struct {
	// Custom element tag for the component
	ComponentTag string `json:"component_tag"`
	// URL of the web component object
	ComponentURL string `json:"component_url"`
}

func (o *JourneyBlockConfig) GetComponentTag() string {
	if o == nil {
		return ""
	}
	return o.ComponentTag
}

func (o *JourneyBlockConfig) GetComponentURL() string {
	if o == nil {
		return ""
	}
	return o.ComponentURL
}
