// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NotificationConfig struct {
	// Email address to receive notifications
	Email *string `json:"email,omitempty"`
	// List of events to subscribe to
	Events []NotificationEvent `json:"events,omitempty"`
}

func (o *NotificationConfig) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *NotificationConfig) GetEvents() []NotificationEvent {
	if o == nil {
		return nil
	}
	return o.Events
}
