// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PatchVersionRequest struct {
	// Required grants for the app in order to call APIs for the installing tenant
	Grants []Grants `json:"grants,omitempty"`
	// Name of the role
	RoleID *string `json:"role_id,omitempty"`
}

func (o *PatchVersionRequest) GetGrants() []Grants {
	if o == nil {
		return nil
	}
	return o.Grants
}

func (o *PatchVersionRequest) GetRoleID() *string {
	if o == nil {
		return nil
	}
	return o.RoleID
}
