// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PatchConfigMetadataRequest struct {
	Category    *string           `json:"category,omitempty"`
	Description *TranslatedString `json:"description,omitempty"`
	// Flag to indicate if the app is in dev mode. If true, the app takes the override properties of components into account.
	DevMode          *bool   `json:"dev_mode,omitempty"`
	DocumentationURL *string `json:"documentation_url,omitempty"`
	// S3 key of the logo file
	LogoURLKey *string `json:"logo_url_key,omitempty"`
	// Name of the app
	Name          *string             `json:"name,omitempty"`
	Notifications *NotificationConfig `json:"notifications,omitempty"`
	Pricing       *Pricing            `json:"pricing,omitempty"`
	// Email address for support requests
	SupportEmail *string `json:"support_email,omitempty"`
}

func (p *PatchConfigMetadataRequest) GetCategory() *string {
	if p == nil {
		return nil
	}
	return p.Category
}

func (p *PatchConfigMetadataRequest) GetDescription() *TranslatedString {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PatchConfigMetadataRequest) GetDevMode() *bool {
	if p == nil {
		return nil
	}
	return p.DevMode
}

func (p *PatchConfigMetadataRequest) GetDocumentationURL() *string {
	if p == nil {
		return nil
	}
	return p.DocumentationURL
}

func (p *PatchConfigMetadataRequest) GetLogoURLKey() *string {
	if p == nil {
		return nil
	}
	return p.LogoURLKey
}

func (p *PatchConfigMetadataRequest) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PatchConfigMetadataRequest) GetNotifications() *NotificationConfig {
	if p == nil {
		return nil
	}
	return p.Notifications
}

func (p *PatchConfigMetadataRequest) GetPricing() *Pricing {
	if p == nil {
		return nil
	}
	return p.Pricing
}

func (p *PatchConfigMetadataRequest) GetSupportEmail() *string {
	if p == nil {
		return nil
	}
	return p.SupportEmail
}
