// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PatchVersionRequest struct {
	// Required grants for the app in order to call APIs for the installing tenant
	Grants []Grants `json:"grants,omitempty"`
	// ID of the manifest to use for this version
	ManifestID *string `json:"manifest_id,omitempty"`
	// Name of the role
	RoleID *string `json:"role_id,omitempty"`
}

func (p *PatchVersionRequest) GetGrants() []Grants {
	if p == nil {
		return nil
	}
	return p.Grants
}

func (p *PatchVersionRequest) GetManifestID() *string {
	if p == nil {
		return nil
	}
	return p.ManifestID
}

func (p *PatchVersionRequest) GetRoleID() *string {
	if p == nil {
		return nil
	}
	return p.RoleID
}
