// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/internal/utils"
)

// PublicConfigurationDescription - Markdown description of the app.
type PublicConfigurationDescription struct {
	// German translation
	De string `json:"de"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (p *PublicConfigurationDescription) GetDe() string {
	if p == nil {
		return ""
	}
	return p.De
}

func (p *PublicConfigurationDescription) GetEn() *string {
	if p == nil {
		return nil
	}
	return p.En
}

type PublicConfigurationPricingType string

const (
	PublicConfigurationPricingTypeFree         PublicConfigurationPricingType = "FREE"
	PublicConfigurationPricingTypeSubscription PublicConfigurationPricingType = "SUBSCRIPTION"
	PublicConfigurationPricingTypeUsageBased   PublicConfigurationPricingType = "USAGE_BASED"
	PublicConfigurationPricingTypeOneTime      PublicConfigurationPricingType = "ONE_TIME"
	PublicConfigurationPricingTypeCustom       PublicConfigurationPricingType = "CUSTOM"
	PublicConfigurationPricingTypeUnknown      PublicConfigurationPricingType = "UNKNOWN"
)

func (e PublicConfigurationPricingType) ToPointer() *PublicConfigurationPricingType {
	return &e
}
func (e *PublicConfigurationPricingType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FREE":
		fallthrough
	case "SUBSCRIPTION":
		fallthrough
	case "USAGE_BASED":
		fallthrough
	case "ONE_TIME":
		fallthrough
	case "CUSTOM":
		fallthrough
	case "UNKNOWN":
		*e = PublicConfigurationPricingType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PublicConfigurationPricingType: %v", v)
	}
}

// PublicConfigurationPricing - Pricing information for the app
type PublicConfigurationPricing struct {
	// How often the subscription is billed
	BillingFrequency *BillingFrequency               `json:"billing_frequency,omitempty"`
	PricingType      *PublicConfigurationPricingType `json:"pricing_type,omitempty"`
}

func (p *PublicConfigurationPricing) GetBillingFrequency() *BillingFrequency {
	if p == nil {
		return nil
	}
	return p.BillingFrequency
}

func (p *PublicConfigurationPricing) GetPricingType() *PublicConfigurationPricingType {
	if p == nil {
		return nil
	}
	return p.PricingType
}

// PublicConfiguration - Public configuration of the published app
type PublicConfiguration struct {
	// ID of the app configuration
	AppID        string        `json:"app_id"`
	Author       *Author       `json:"author,omitempty"`
	BlueprintRef *BlueprintRef `json:"blueprint_ref,omitempty"`
	// Category of the app.
	Category   *string         `json:"category,omitempty"`
	Components []BaseComponent `json:"components"`
	// Timestamp when the app version is deprecated
	DeprecatedAt *string                         `json:"deprecated_at,omitempty"`
	Description  *PublicConfigurationDescription `json:"description,omitempty"`
	// Flag to indicate if the app is in dev mode.
	DevMode *bool `json:"dev_mode,omitempty"`
	// URL of the app documentation.
	DocumentationURL *string `json:"documentation_url,omitempty"`
	// URL of the app icon.
	IconURL *string `json:"icon_url,omitempty"`
	// Flag to indicate if the app is in beta.
	IsBeta *bool `json:"is_beta,omitempty"`
	// Latest version of the app
	LatestVersion *string `json:"latest_version,omitempty"`
	// Name of the app
	Name string `json:"name"`
	// Organization ID of the app owner
	OwnerOrgID string                      `json:"owner_org_id"`
	Pricing    *PublicConfigurationPricing `json:"pricing,omitempty"`
	// Flag to indicate if the app is public.
	Public *bool `default:"true" json:"public"`
	Role   *Role `json:"role,omitempty"`
	// Email address for support requests
	SupportEmail *string `json:"support_email,omitempty"`
	// Version of the app that is installed
	Version string `json:"version"`
	// List of available versions of the app
	Versions []ConfigurationVersion `json:"versions,omitempty"`
}

func (p PublicConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PublicConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"app_id", "components", "name", "owner_org_id", "version"}); err != nil {
		return err
	}
	return nil
}

func (p *PublicConfiguration) GetAppID() string {
	if p == nil {
		return ""
	}
	return p.AppID
}

func (p *PublicConfiguration) GetAuthor() *Author {
	if p == nil {
		return nil
	}
	return p.Author
}

func (p *PublicConfiguration) GetBlueprintRef() *BlueprintRef {
	if p == nil {
		return nil
	}
	return p.BlueprintRef
}

func (p *PublicConfiguration) GetCategory() *string {
	if p == nil {
		return nil
	}
	return p.Category
}

func (p *PublicConfiguration) GetComponents() []BaseComponent {
	if p == nil {
		return []BaseComponent{}
	}
	return p.Components
}

func (p *PublicConfiguration) GetDeprecatedAt() *string {
	if p == nil {
		return nil
	}
	return p.DeprecatedAt
}

func (p *PublicConfiguration) GetDescription() *PublicConfigurationDescription {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PublicConfiguration) GetDevMode() *bool {
	if p == nil {
		return nil
	}
	return p.DevMode
}

func (p *PublicConfiguration) GetDocumentationURL() *string {
	if p == nil {
		return nil
	}
	return p.DocumentationURL
}

func (p *PublicConfiguration) GetIconURL() *string {
	if p == nil {
		return nil
	}
	return p.IconURL
}

func (p *PublicConfiguration) GetIsBeta() *bool {
	if p == nil {
		return nil
	}
	return p.IsBeta
}

func (p *PublicConfiguration) GetLatestVersion() *string {
	if p == nil {
		return nil
	}
	return p.LatestVersion
}

func (p *PublicConfiguration) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PublicConfiguration) GetOwnerOrgID() string {
	if p == nil {
		return ""
	}
	return p.OwnerOrgID
}

func (p *PublicConfiguration) GetPricing() *PublicConfigurationPricing {
	if p == nil {
		return nil
	}
	return p.Pricing
}

func (p *PublicConfiguration) GetPublic() *bool {
	if p == nil {
		return nil
	}
	return p.Public
}

func (p *PublicConfiguration) GetRole() *Role {
	if p == nil {
		return nil
	}
	return p.Role
}

func (p *PublicConfiguration) GetSupportEmail() *string {
	if p == nil {
		return nil
	}
	return p.SupportEmail
}

func (p *PublicConfiguration) GetVersion() string {
	if p == nil {
		return ""
	}
	return p.Version
}

func (p *PublicConfiguration) GetVersions() []ConfigurationVersion {
	if p == nil {
		return nil
	}
	return p.Versions
}
