// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Role struct {
	// Required grants for the app in order to call APIs for the installing tenant
	Grants []Grants `json:"grants,omitempty"`
	// Name of the role
	ID *string `json:"id,omitempty"`
}

func (o *Role) GetGrants() []Grants {
	if o == nil {
		return nil
	}
	return o.Grants
}

func (o *Role) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}
