// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TranslatedString struct {
	// German translation
	De *string `json:"de,omitempty"`
	// English translation
	En *string `json:"en,omitempty"`
}

func (o *TranslatedString) GetDe() *string {
	if o == nil {
		return nil
	}
	return o.De
}

func (o *TranslatedString) GetEn() *string {
	if o == nil {
		return nil
	}
	return o.En
}
