// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UploadFilePayload struct {
	// ID of the app configuration. Required for app updates.
	AppID *string `json:"app_id,omitempty"`
}

func (o *UploadFilePayload) GetAppID() *string {
	if o == nil {
		return nil
	}
	return o.AppID
}
