// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-app/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk"
	"github.com/epilot-dev/terraform-provider-epilot-app/internal/sdk/models/operations"
	speakeasy_listvalidators "github.com/epilot-dev/terraform-provider-epilot-app/internal/validators/listvalidators"
	speakeasy_objectvalidators "github.com/epilot-dev/terraform-provider-epilot-app/internal/validators/objectvalidators"
	speakeasy_stringvalidators "github.com/epilot-dev/terraform-provider-epilot-app/internal/validators/stringvalidators"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AppResource{}
var _ resource.ResourceWithImportState = &AppResource{}

func NewAppResource() resource.Resource {
	return &AppResource{}
}

// AppResource defines the resource implementation.
type AppResource struct {
	client *sdk.SDK
}

// AppResourceModel describes the resource data model.
type AppResourceModel struct {
	AppID             types.String               `tfsdk:"app_id"`
	Components        []tfTypes.BaseComponent    `tfsdk:"components"`
	Enabled           types.Bool                 `tfsdk:"enabled"`
	InstallationAudit *tfTypes.InstallationAudit `tfsdk:"installation_audit"`
	InstalledVersion  types.String               `tfsdk:"installed_version"`
	InstallerOrgID    types.String               `tfsdk:"installer_org_id"`
	Name              types.String               `tfsdk:"name"`
	OptionValues      []tfTypes.OptionsRef       `tfsdk:"option_values"`
}

func (r *AppResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_app"
}

func (r *AppResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "App Resource",
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Required: true,
			},
			"components": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"custom_journey_block": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"component_type": schema.StringAttribute{
									Computed:    true,
									Description: `must be "CUSTOM_JOURNEY_BLOCK"`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"CUSTOM_JOURNEY_BLOCK",
										),
									},
								},
								"configuration": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"component_args": schema.ListNestedAttribute{
											Computed: true,
											NestedObject: schema.NestedAttributeObject{
												Attributes: map[string]schema.Attribute{
													"boolean": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"description": schema.SingleNestedAttribute{
																Computed: true,
																Attributes: map[string]schema.Attribute{
																	"de": schema.StringAttribute{
																		Computed:    true,
																		Description: `German translation`,
																	},
																	"en": schema.StringAttribute{
																		Computed:    true,
																		Description: `English translation`,
																	},
																},
																Description: `Description of what this component arg does`,
															},
															"key": schema.StringAttribute{
																Computed:    true,
																Description: `Unique identifier for this component arg`,
															},
															"label": schema.SingleNestedAttribute{
																Computed: true,
																Attributes: map[string]schema.Attribute{
																	"de": schema.StringAttribute{
																		Computed:    true,
																		Description: `German translation`,
																	},
																	"en": schema.StringAttribute{
																		Computed:    true,
																		Description: `English translation`,
																	},
																},
																Description: `Human-readable label for the component arg`,
															},
															"required": schema.BoolAttribute{
																Computed:    true,
																Default:     booldefault.StaticBool(false),
																Description: `Flag to indicate if this option is required. Default: false`,
															},
															"type": schema.StringAttribute{
																Computed:    true,
																Description: `must be one of ["text", "boolean", "enum"]`,
																Validators: []validator.String{
																	stringvalidator.OneOf(
																		"text",
																		"boolean",
																		"enum",
																	),
																},
															},
														},
														Validators: []validator.Object{
															objectvalidator.ConflictsWith(path.Expressions{
																path.MatchRelative().AtParent().AtName("text"),
																path.MatchRelative().AtParent().AtName("enum"),
															}...),
														},
													},
													"enum": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"description": schema.SingleNestedAttribute{
																Computed: true,
																Attributes: map[string]schema.Attribute{
																	"de": schema.StringAttribute{
																		Computed:    true,
																		Description: `German translation`,
																	},
																	"en": schema.StringAttribute{
																		Computed:    true,
																		Description: `English translation`,
																	},
																},
																Description: `Description of what this component arg does`,
															},
															"is_multi": schema.BoolAttribute{
																Computed:    true,
																Default:     booldefault.StaticBool(false),
																Description: `If true, allows selection of multiple values. Default: false`,
															},
															"key": schema.StringAttribute{
																Computed:    true,
																Description: `Unique identifier for this component arg`,
															},
															"label": schema.SingleNestedAttribute{
																Computed: true,
																Attributes: map[string]schema.Attribute{
																	"de": schema.StringAttribute{
																		Computed:    true,
																		Description: `German translation`,
																	},
																	"en": schema.StringAttribute{
																		Computed:    true,
																		Description: `English translation`,
																	},
																},
																Description: `Human-readable label for the component arg`,
															},
															"options": schema.ListNestedAttribute{
																Computed: true,
																NestedObject: schema.NestedAttributeObject{
																	Attributes: map[string]schema.Attribute{
																		"id": schema.StringAttribute{
																			Computed:    true,
																			Description: `Unique identifier for the option`,
																		},
																		"label": schema.SingleNestedAttribute{
																			Computed: true,
																			Attributes: map[string]schema.Attribute{
																				"de": schema.StringAttribute{
																					Computed:    true,
																					Description: `German translation`,
																				},
																				"en": schema.StringAttribute{
																					Computed:    true,
																					Description: `English translation`,
																				},
																			},
																			Description: `Display label for the option`,
																		},
																	},
																},
																Description: `List of options for enum type`,
																Validators: []validator.List{
																	listvalidator.SizeAtLeast(1),
																},
															},
															"required": schema.BoolAttribute{
																Computed:    true,
																Default:     booldefault.StaticBool(false),
																Description: `Flag to indicate if this option is required. Default: false`,
															},
															"type": schema.StringAttribute{
																Computed:    true,
																Description: `must be one of ["text", "boolean", "enum"]`,
																Validators: []validator.String{
																	stringvalidator.OneOf(
																		"text",
																		"boolean",
																		"enum",
																	),
																},
															},
														},
														Validators: []validator.Object{
															objectvalidator.ConflictsWith(path.Expressions{
																path.MatchRelative().AtParent().AtName("text"),
																path.MatchRelative().AtParent().AtName("boolean"),
															}...),
														},
													},
													"text": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"description": schema.SingleNestedAttribute{
																Computed: true,
																Attributes: map[string]schema.Attribute{
																	"de": schema.StringAttribute{
																		Computed:    true,
																		Description: `German translation`,
																	},
																	"en": schema.StringAttribute{
																		Computed:    true,
																		Description: `English translation`,
																	},
																},
																Description: `Description of what this component arg does`,
															},
															"key": schema.StringAttribute{
																Computed:    true,
																Description: `Unique identifier for this component arg`,
															},
															"label": schema.SingleNestedAttribute{
																Computed: true,
																Attributes: map[string]schema.Attribute{
																	"de": schema.StringAttribute{
																		Computed:    true,
																		Description: `German translation`,
																	},
																	"en": schema.StringAttribute{
																		Computed:    true,
																		Description: `English translation`,
																	},
																},
																Description: `Human-readable label for the component arg`,
															},
															"required": schema.BoolAttribute{
																Computed:    true,
																Default:     booldefault.StaticBool(false),
																Description: `Flag to indicate if this option is required. Default: false`,
															},
															"type": schema.StringAttribute{
																Computed:    true,
																Description: `must be one of ["text", "boolean", "enum"]`,
																Validators: []validator.String{
																	stringvalidator.OneOf(
																		"text",
																		"boolean",
																		"enum",
																	),
																},
															},
														},
														Validators: []validator.Object{
															objectvalidator.ConflictsWith(path.Expressions{
																path.MatchRelative().AtParent().AtName("boolean"),
																path.MatchRelative().AtParent().AtName("enum"),
															}...),
														},
													},
												},
											},
											Description: `Arguments to pass to the component`,
										},
										"component_size": schema.NumberAttribute{
											Computed:    true,
											Description: `Size of the bundle in bytes`,
										},
										"component_tag": schema.StringAttribute{
											Computed:    true,
											Description: `Custom element tag for the component`,
										},
										"component_url": schema.StringAttribute{
											Computed:    true,
											Description: `URL of the web component object`,
										},
									},
								},
								"description": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"de": schema.StringAttribute{
											Computed:    true,
											Description: `German translation`,
										},
										"en": schema.StringAttribute{
											Computed:    true,
											Description: `English translation`,
										},
									},
									Description: `Description of the component`,
								},
								"id": schema.StringAttribute{
									Computed:    true,
									Description: `Unique identifier for the component`,
								},
								"name": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"de": schema.StringAttribute{
											Computed:    true,
											Description: `German translation`,
										},
										"en": schema.StringAttribute{
											Computed:    true,
											Description: `English translation`,
										},
									},
									Description: `Name of the component`,
								},
								"options": schema.ListNestedAttribute{
									Computed: true,
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"description": schema.StringAttribute{
												Computed:    true,
												Description: `Detailed description of what this configuration option does`,
											},
											"key": schema.StringAttribute{
												Computed:    true,
												Description: `Unique identifier for this configuration option`,
											},
											"label": schema.StringAttribute{
												Computed:    true,
												Description: `Human-readable label for the configuration option`,
											},
											"required": schema.BoolAttribute{
												Computed:    true,
												Description: `Flag to indicate if this option is required`,
											},
											"type": schema.StringAttribute{
												Computed:    true,
												Description: `must be one of ["text", "number", "boolean", "secret"]`,
												Validators: []validator.String{
													stringvalidator.OneOf(
														"text",
														"number",
														"boolean",
														"secret",
													),
												},
											},
											"value": schema.StringAttribute{
												Computed:    true,
												Description: `The configured value for this option. Is only present when the component is installed.`,
											},
										},
									},
									Description: `List of options for the app component`,
								},
							},
							Validators: []validator.Object{
								objectvalidator.ConflictsWith(path.Expressions{
									path.MatchRelative().AtParent().AtName("portal_extension"),
								}...),
							},
						},
						"portal_extension": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"component_type": schema.StringAttribute{
									Computed:    true,
									Description: `must be "PORTAL_EXTENSION"`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"PORTAL_EXTENSION",
										),
									},
								},
								"configuration": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"hooks": schema.ListNestedAttribute{
											Computed: true,
											NestedObject: schema.NestedAttributeObject{
												Attributes: map[string]schema.Attribute{
													"auth": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"headers": schema.MapAttribute{
																Computed:    true,
																ElementType: types.StringType,
															},
															"method": schema.StringAttribute{
																Computed: true,
															},
															"type": schema.StringAttribute{
																Computed: true,
															},
															"url": schema.StringAttribute{
																Computed: true,
															},
														},
													},
													"call": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"headers": schema.MapAttribute{
																Computed:    true,
																ElementType: types.StringType,
															},
															"params": schema.MapAttribute{
																Computed:    true,
																ElementType: types.StringType,
															},
															"url": schema.StringAttribute{
																Computed: true,
															},
														},
													},
													"id": schema.StringAttribute{
														Computed: true,
													},
													"interval": schema.ListAttribute{
														Computed:    true,
														ElementType: types.StringType,
													},
													"name": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"de": schema.StringAttribute{
																Computed:    true,
																Description: `German translation`,
															},
															"en": schema.StringAttribute{
																Computed:    true,
																Description: `English translation`,
															},
														},
													},
													"type": schema.StringAttribute{
														Computed: true,
													},
												},
											},
										},
										"id": schema.StringAttribute{
											Computed: true,
										},
										"links": schema.ListNestedAttribute{
											Computed: true,
											NestedObject: schema.NestedAttributeObject{
												Attributes: map[string]schema.Attribute{
													"auth": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"headers": schema.MapAttribute{
																Computed:    true,
																ElementType: types.StringType,
															},
															"method": schema.StringAttribute{
																Computed: true,
															},
															"type": schema.StringAttribute{
																Computed: true,
															},
															"url": schema.StringAttribute{
																Computed: true,
															},
														},
													},
													"condition": schema.StringAttribute{
														Computed: true,
													},
													"description": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"de": schema.StringAttribute{
																Computed:    true,
																Description: `German translation`,
															},
															"en": schema.StringAttribute{
																Computed:    true,
																Description: `English translation`,
															},
														},
													},
													"id": schema.StringAttribute{
														Computed: true,
													},
													"name": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"de": schema.StringAttribute{
																Computed:    true,
																Description: `German translation`,
															},
															"en": schema.StringAttribute{
																Computed:    true,
																Description: `English translation`,
															},
														},
													},
													"redirect": schema.SingleNestedAttribute{
														Computed: true,
														Attributes: map[string]schema.Attribute{
															"params": schema.MapAttribute{
																Computed:    true,
																ElementType: types.StringType,
															},
															"url": schema.StringAttribute{
																Computed: true,
															},
														},
													},
													"type": schema.StringAttribute{
														Computed: true,
													},
												},
											},
										},
									},
								},
								"description": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"de": schema.StringAttribute{
											Computed:    true,
											Description: `German translation`,
										},
										"en": schema.StringAttribute{
											Computed:    true,
											Description: `English translation`,
										},
									},
									Description: `Description of the component`,
								},
								"id": schema.StringAttribute{
									Computed:    true,
									Description: `Unique identifier for the component`,
								},
								"name": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"de": schema.StringAttribute{
											Computed:    true,
											Description: `German translation`,
										},
										"en": schema.StringAttribute{
											Computed:    true,
											Description: `English translation`,
										},
									},
									Description: `Name of the component`,
								},
								"options": schema.ListNestedAttribute{
									Computed: true,
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"description": schema.StringAttribute{
												Computed:    true,
												Description: `Detailed description of what this configuration option does`,
											},
											"key": schema.StringAttribute{
												Computed:    true,
												Description: `Unique identifier for this configuration option`,
											},
											"label": schema.StringAttribute{
												Computed:    true,
												Description: `Human-readable label for the configuration option`,
											},
											"required": schema.BoolAttribute{
												Computed:    true,
												Description: `Flag to indicate if this option is required`,
											},
											"type": schema.StringAttribute{
												Computed:    true,
												Description: `must be one of ["text", "number", "boolean", "secret"]`,
												Validators: []validator.String{
													stringvalidator.OneOf(
														"text",
														"number",
														"boolean",
														"secret",
													),
												},
											},
											"value": schema.StringAttribute{
												Computed:    true,
												Description: `The configured value for this option. Is only present when the component is installed.`,
											},
										},
									},
									Description: `List of options for the app component`,
								},
								"origin": schema.StringAttribute{
									Computed:    true,
									Description: `must be one of ["END_CUSTOMER_PORTAL", "INSTALLER_PORTAL"]`,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"END_CUSTOMER_PORTAL",
											"INSTALLER_PORTAL",
										),
									},
								},
							},
							Validators: []validator.Object{
								objectvalidator.ConflictsWith(path.Expressions{
									path.MatchRelative().AtParent().AtName("custom_journey_block"),
								}...),
							},
						},
					},
				},
				Description: `List of component configurations for the installed version`,
			},
			"enabled": schema.BoolAttribute{
				Computed:    true,
				Default:     booldefault.StaticBool(true),
				Description: `Flag to indicate if the app is enabled. Enabled is set to true when required option values are set. Default: true`,
			},
			"installation_audit": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Computed:    true,
						Description: `Timestamp of the creation`,
					},
					"created_by": schema.StringAttribute{
						Computed:    true,
						Description: `User ID of the creator`,
					},
					"updated_at": schema.StringAttribute{
						Computed:    true,
						Description: `Timestamp of the last update`,
					},
					"updated_by": schema.StringAttribute{
						Computed:    true,
						Description: `User ID of the last updater`,
					},
				},
				Description: `Audit information for the app`,
			},
			"installed_version": schema.StringAttribute{
				Computed:    true,
				Description: `Version of the app that is installed`,
			},
			"installer_org_id": schema.StringAttribute{
				Computed:    true,
				Description: `Unique identifier for the organization the app is installed in`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Name of the app`,
			},
			"option_values": schema.ListNestedAttribute{
				Computed: true,
				Optional: true,
				NestedObject: schema.NestedAttributeObject{
					Validators: []validator.Object{
						speakeasy_objectvalidators.NotNull(),
					},
					Attributes: map[string]schema.Attribute{
						"component_id": schema.StringAttribute{
							Computed:    true,
							Optional:    true,
							Description: `ID of the component these values are for. Not Null`,
							Validators: []validator.String{
								speakeasy_stringvalidators.NotNull(),
							},
						},
						"options": schema.ListNestedAttribute{
							Computed: true,
							Optional: true,
							NestedObject: schema.NestedAttributeObject{
								Validators: []validator.Object{
									speakeasy_objectvalidators.NotNull(),
								},
								Attributes: map[string]schema.Attribute{
									"key": schema.StringAttribute{
										Computed:    true,
										Optional:    true,
										Description: `Key matching a config_option from the component. Not Null`,
										Validators: []validator.String{
											speakeasy_stringvalidators.NotNull(),
										},
									},
									"value": schema.StringAttribute{
										Computed:    true,
										Optional:    true,
										Description: `The configured value for this option. Not Null`,
										Validators: []validator.String{
											speakeasy_stringvalidators.NotNull(),
										},
									},
								},
							},
							Description: `Not Null`,
							Validators: []validator.List{
								speakeasy_listvalidators.NotNull(),
							},
						},
					},
				},
				Description: `Configuration values for the app components`,
			},
		},
	}
}

func (r *AppResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *AppResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *AppResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	installRequest := data.ToSharedInstallRequest()
	var appID string
	appID = data.AppID.ValueString()

	request := operations.InstallRequest{
		InstallRequest: installRequest,
		AppID:          appID,
	}
	res, err := r.client.AppInstallation.Install(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 201 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Object != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromOperationsInstallResponseBody(res.Object)
	refreshPlan(ctx, plan, &data, resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *AppResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	var appID string
	appID = data.AppID.ValueString()

	request := operations.GetInstallationRequest{
		AppID: appID,
	}
	res, err := r.client.AppInstallation.GetInstallation(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Installation != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedInstallation(res.Installation)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *AppResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	installRequest := data.ToSharedInstallRequest()
	var appID string
	appID = data.AppID.ValueString()

	request := operations.PatchInstallationRequest{
		InstallRequest: installRequest,
		AppID:          appID,
	}
	res, err := r.client.AppInstallation.PatchInstallation(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 204 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	refreshPlan(ctx, plan, &data, resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *AppResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	var appID string
	appID = data.AppID.ValueString()

	request := operations.UninstallRequest{
		AppID: appID,
	}
	res, err := r.client.AppInstallation.Uninstall(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 204 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *AppResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("app_id"), req.ID)...)
}
