// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type BlueprintRef struct {
	JobID      types.String `tfsdk:"job_id"`
	ManifestID types.String `tfsdk:"manifest_id"`
}
