// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Hooks struct {
	Auth     *PortalAuth       `tfsdk:"auth"`
	Call     *Call             `tfsdk:"call"`
	ID       types.String      `tfsdk:"id"`
	Interval []types.String    `tfsdk:"interval"`
	Name     *TranslatedString `tfsdk:"name"`
	Type     types.String      `tfsdk:"type"`
}
