// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneyBlockConfig struct {
	ComponentArgs []JourneyBlockComponentArgs `tfsdk:"component_args"`
	ComponentSize types.Number                `tfsdk:"component_size"`
	ComponentTag  types.String                `tfsdk:"component_tag"`
	ComponentURL  types.String                `tfsdk:"component_url"`
}
