// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type JourneyBlockComponentArgs struct {
	Text    *TextArgSchemas `tfsdk:"text" tfPlanOnly:"true"`
	Boolean *TextArgSchemas `tfsdk:"boolean" tfPlanOnly:"true"`
	Enum    *EnumArgSchemas `tfsdk:"enum" tfPlanOnly:"true"`
}
