// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type JourneyBlockComponentSchemas struct {
	ComponentType types.String               `tfsdk:"component_type"`
	Configuration JourneyBlockConfig         `tfsdk:"configuration"`
	Description   *SchemasTextArgDescription `tfsdk:"description"`
	ID            types.String               `tfsdk:"id"`
	Name          *SchemasTextArgDescription `tfsdk:"name"`
	Options       []Options                  `tfsdk:"options"`
}
