// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type PortalAuth struct {
	Headers map[string]types.String `tfsdk:"headers"`
	Method  types.String            `tfsdk:"method"`
	Type    types.String            `tfsdk:"type"`
	URL     types.String            `tfsdk:"url"`
}
