// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Redirect struct {
	Params map[string]types.String `tfsdk:"params"`
	URL    types.String            `tfsdk:"url"`
}
