// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SchemasOptions struct {
	ID    types.String              `tfsdk:"id"`
	Label SchemasTextArgDescription `tfsdk:"label"`
}
