// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type TextArgSchemas struct {
	Description *SchemasTextArgDescription `tfsdk:"description"`
	Key         types.String               `tfsdk:"key"`
	Label       SchemasTextArgDescription  `tfsdk:"label"`
	Required    types.Bool                 `tfsdk:"required"`
	Type        types.String               `tfsdk:"type"`
}
